language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ]; then mvn -Prelease deploy -Dgpg.skip=true --settings mySettings.xml;
  else mvn package; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb21bc5d1981f1d7c5ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
